# This play book is to create ec2 records and route53 records using ansible
- name: Create ec2 and r53 records
  hosts: localhost
  connection: local
  vars:
    sg_id: sg-088988091b81eae5c
    subnet_id: subnet-04d82804a30fa7790
    ami_id: ami-09c813fb71547fc4f
    instances:
      - mysql
      - backend
      - frontend
    zone: laven.cloud
  tasks:
    - name: Install bocore and boto3
      ansible.builtin.pip:
        name:
          - boto3
          - botocore
        executable: pip3.9
    - name: Create ec2 instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        vpc_subnet_id: "{{ subnet_id }}"
        instance_type: "t3.micro"
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
      loop: "{{ instances }}"
      register: ec2_instances

    - name: Print ec2_instances
      ansible.builtin.debug:
        msg: "{{ ec2_instances }}"

    # Create private route 53 records
    - name: Create private route 53 records
      amazon.aws.route53:
        state: present
        zone: "{{ zone }}"
        record: "{{ item.item }}.{{ zone }}"
        type: "A"
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}"
        wait: true
        overwrite: true
      loop: "{{ ec2_instances.results }}"
      when: item.item != frontend

    # Create public DNS record for frontend
    - name: Public DNS record for frontend
      vars:
        public_name: expense
      amazon.aws.route53:
        state: present
        zone: "{{ zone }}"
        record: "{{ public_name }}.{{ zone }}"
        type: "A"
        ttl: 1
        value: "{{ item.instances[0].public_ip_address }}"
        wait: true
        overwrite: true
      loop: "{{ ec2_instances.results }}"
      when: item.item == "frontend"