# This playbook is to create EC2 instances and Route 53 records using Ansible
- name: Create EC2 and Route 53 records for Roboshop
  hosts: localhost
  connection: local
  vars:
    sg_id: sg-088988091b81eae5c
    subnet_id: subnet-04d82804a30fa7790
    ami_id: ami-09c813fb71547fc4f
    instances:
      - catalogue
      - cart
      - user
      - shipping
      - payment
      - frontend-roboshop
      - mongodb
      - mysql
      - rabbitmq
      - redis
      - dispatch
    zone: devopsrobo.shop
  tasks:
    - name: Install boto3 and botocore
      ansible.builtin.pip:
        name:
          - boto3
          - botocore
        executable: pip3.9

    - name: Create EC2 instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        vpc_subnet_id: "{{ subnet_id }}"
        instance_type: "t3.micro"
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
      loop: "{{ instances }}"
      register: ec2_instances

    - name: Print EC2 instances
      ansible.builtin.debug:
        msg: "{{ ec2_instances }}"

    # Combined DNS task
    - name: Create DNS records
      amazon.aws.route53:
        state: present
        zone: "{{ zone }}"
        #record: "{{ (item.item == 'frontend-roboshop') | ternary({{ zone }}, item.item) }}.{{ zone }}" # ternary(zone, item.item + '.' + zone)
        record: "{{ (item.item == 'frontend-roboshop') | ternary(zone, item.item + '.' + zone) }}"
        type: "A"
        ttl: 1
        value: "{{ (item.item == 'frontend') | ternary(item.instances[0].public_ip_address, item.instances[0].private_ip_address) }}"
        wait: true
        overwrite: true
      loop: "{{ ec2_instances.results }}"